name: Testing the basic communication between the runner and the server
 
on: [push]
 
jobs:
 ssh-conection:
   runs-on: ubuntu-latest
 
   steps:
     - name: executing remote ssh commands using password
       uses: appleboy/ssh-action@v0.1.9
       with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USER }}
         key: ${{ secrets.SSH_KEY }}
         script: |
          whoami
          ls -al
