name: My Workflow
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run action

      uses: abrahamNtd/poc-git-action@feature/docker_action

      # Put an example of your mandatory inputs here
      with:
        myInput: world
